name: Test Report

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed

permissions:
  checks: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v9
      with:
        workflow: CI
        workflow_conclusion: completed
        path: artifacts

    - name: Debug - List downloaded artifacts
      run: |
        echo "Listing artifact directories:"
        find artifacts -type d
        echo "Listing all XML files:"
        find artifacts -name "*.xml"

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: "artifacts/**/*.xml"  # Simplified pattern to find any XML file
