name: Test Report

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed

permissions:
  checks: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v9
      with:
        workflow: CI
        commit: ${{ github.event.workflow_run.head_sha }}
        path: artifacts

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: "artifacts/**/junit/*.xml"
