name: Test Report

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed

permissions:
  checks: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v9
      with:
        workflow: CI
        commit: ${{ github.event.workflow_run.head_sha }}
        path: artifacts
    
    - name: Publish Test Report
      uses: dorny/test-reporter@v2
      with:
        name: Pytest Results
        path: artifacts/test-results-*/test-results-*.xml
        reporter: jest-junit
        fail-on-error: false